### PR TITLE
Reimplement clawdata.dt_max at coarsest grid resolution

### PR DESCRIPTION
**Pull request by kbarnhart**
@dlgeorge this PR addes @rypjones's two changes for honoring the maximum dt at the coarsest grid resolution.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@dlgeorge @rypjones FYI I'm getting an initial dt log message of "automatically setting initial dt to    7.7162922918007988" when I've set the dt_max to 0.1

Not sure if it indicates that this isn't quite right or that I've done something else not quite right... 

But noting here before I forget.

**Comment by kbarnhart** [comment]
@dlgeorge @rypjones I've tried to dig into this a bit more to see what's happening (you can see my temporary debugging lines in the last commit)...

Based on looking at these debug printouts it appears to me that the variable dtv2 (which stores the max dt for the coarsest AMR level) is read in correctly, but then somewhere between being read in and being used it gets set to zero... I'm having a hard time figuring out where. 

For example, my debug from reading in yields:
```
 Reading data file: amr2ez.data
         first 5 lines are comments and will be skipped
   possk(1)    9.9999999999999998E-017
   dtv2   0.10000000000000001
   cflv1   0.50000000000000000
   cfl   0.25000000000000000
   nv1       100000
```

And then when it comes to actually using the timestep limiter I find:

```
   possk(1)    9.9999999999999998E-017
   possk(1)    105.28998632059687
   dtv2    0.0000000000000000
   automatically setting initial dt to    0.0000000000000000
  this run has variable time refinement =  T
```

I did make .program so I could grep on the full set of source code and couldn't find anything obvious in there for where it gets set to zero...

**Comment by geoflows** [comment]
@kbarnhart @rypjones ...hmm...that variable is in a common block maybe...so could be extra tricky to figure out. (I guess I'll wait to merge. ?).

**Comment by kbarnhart** [comment]
@dlgeorge I wouldn't merge this yet... I suspect the issue has to do with when/where/if dtv2 is declared as a global variable and/or passed around appropriately.

**Comment by kbarnhart** [comment]
@dlgeorge declaring dtv2 as a global variable in geoclaw_mod.f90 results in the max dt being honored for me and @rypjones (his fix). I admit I don't know enough about fortran program design to know whether this is a terrible fix or totally fine.

**Comment by geoflows** [comment]
@kbarnhart hmm, adding to the geoclaw module as a global variable might need some more investigation...seems potentially problematic, but might check out to be fine. but, good to know the other behavior...seems like we'll figure it out.

**Comment by kbarnhart** [comment]
@dlgeorge I've now looked into this a bit more carefully and I think its as good as I can get it. 

As best as I can tell, before this PR, the variable dtv2 was never declared anywhere. 

The input value set in setrun.py as clawdata.max_dt was read into it in amr2ez_geo, but then it wasn't ever used (id'd by greping on make .program's output). 

Based on our conversation, it sounds like declaring this variable in geoclaw_mod is the most sensible thing to do (which is apparently what I/Ryan did initially).

**Comment by geoflows** [comment]
do any of the changes add new variables to ascii input?...or is everything in modules?

**Pull request merged**
